version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/code
      - /code/node_modules/